name: exohood
version: 0.11.1.0
summary: "Exohood: the secure, public, traceable cryptocurrency https://exohood.com"
description: |
    exohood is a secure, public and decentralised digital currency.
    You are your bank and you control your funds.
grade: devel
confinement: strict

apps:
    exohood:
        daemon: forking
        command: |
          exohood-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/exohood.conf
        plugs:
            - network
            - network-bind
    exohood-wallet-rpc:
        command: |
          exohood-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    exohood-wallet-cli:
        command: |
          exohood-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/exohood.conf: etc/exohood.conf
            contrib/snap/exohood-wrapper: bin/exohood-wrapper
        prime:
            - etc
            - bin
